dev-MM etap pierwszy
MlabCommunity/files pull request #1
Opened 2022-07-09 20:14 UTC by Madzionator

2022-07-12 06:57 UTC, adambednarz requested changes
Ogólnie spoko ale nie do końca poprawnie zrozumiana i zaimplementowana została koncepcja fasady, oraz brakuje testów

2022-07-12 06:57 UTC, adambednarz commented on Lapka.Files.Api/Controllers/StorageController.cs
> +    public record FormFileRecord(IFormFile File);
Do usunięcia/przeniesienia z kontrolera

2022-07-12 06:57 UTC, adambednarz commented on Lapka.Files.Api/Controllers/StorageController.cs
> +        => await _storageFacade.DeleteFile(id);
Tu i we wcześniejszych endpointach niejawna zwrotka tzn. patrząc na kontroler powinniśmy już wiedzieć co dana metoda zwraca a u Ciebie widać to dopiero jak się wejdzie w fasade. Ogólnie IActionResult jest zarezerwowany dla metod kontrolerów i pchanie go dalej nie bardzo ma sens

2022-07-12 06:57 UTC, adambednarz commented on Lapka.Files.Api/Facade/IStorageFacade.cs
> +public interface IStorageFacade
Nie do końca poprawnie zrozumiana i zaimplementowana fasada - aktualnie pełni ona bardziej rolę serwisu a miała być "opakowaniem" klienta minio.
Poza tym nie powinno to się znajdować w warstwie API oraz nie powinno zwracać IActionResult

2022-07-12 06:57 UTC, adambednarz commented on Lapka.Files.Api/Facade/IStorageFacade.cs
> +    Task<ActionResult> GetFile(Guid id);
Wszędzie niżej zwracasz interfejs a tu klase

2022-07-12 06:57 UTC, adambednarz commented on Lapka.Files.Api/Facade/StorageFacade.cs
> +        try
Try catch dobrze zabezpiecza kod alee na dłuższą metę niestety się nie sprawdza ;/ 
W przypadku bardziej skomplikowanych metod użycie w nich try catcha powoduje że kod jest bardziej skomplikowany, mniej czytelny a jak jeszcze dojdą if i zagnieżdżenia to masakra :)

Tak więc tutaj wyłącznie sprawdzamy czy fille == null jeżeli tak to rzucamy wyjątek aaaa dopiero w infrastrukturze dodajemy middleware który nam to obsłuży i odpowiednio zmapuje 

Z tego co pamietam Adrian miał to fajnie zrobione więc przegadajcie to

2022-07-12 06:57 UTC, adambednarz commented on Lapka.Files.Api/Facade/StorageFacade.cs
> +            _logger.LogError(pex, "error downloading the file");
błędy do logów tez zdecydowanie lepiej jest obsłużyć jednorazowo w dedykowanym middleware niż za każdym razem w  kodzie

2022-07-12 06:57 UTC, adambednarz commented on Lapka.Files.Api/Properties/launchSettings.json
> +      "applicationUrl": "https://localhost:7282;http://localhost:5282",
Warto już na wstępie skonfigurować sobie odpwiednie porty i aby uniknąć komunikatów i błędów z SSl można użyć wyłącznie http

2022-07-12 06:57 UTC, adambednarz commented on Lapka.Files.Api/appsettings.json
> +  "ConnectionStrings": {
Konfiguracja Postgresa oraz Minio powinna się znaleźć w settingsach dedykowanych odpowiedniemu środowisku. W tym przypadku Development jest to o tyle ważne bo jak postawisz nowe środowisko i zapomnisz o nadpisaniu zmiennych to zaciągnie z głównego pliku i bedzie powodowało błędy lub aplikacja nie wstanie

2022-07-12 06:57 UTC, adambednarz commented on Lapka.Files.Core/DataBase/DataContext.cs
> +namespace Lapka.Files.Core.DataBase;
To powinno się znaleźć w infrastrukturze

2022-07-12 06:57 UTC, adambednarz commented on Lapka.Files.Core/DataBase/DataContext.cs
> +    {
Bardzo fajny pomysł z taką globalną konfiguracją dat. 
Dwie uwagi 
- stosujemy klamerki zarówno w if jak i foreach (raz dodałaś w if a drugi raz nie - umawiamy się że dodajemy wszędzie)
- jeżeli to backend odpowiada za przypisywanie dat to zawsze stosujemy UTC a nie local

2022-07-12 06:57 UTC, adambednarz commented on Lapka.Files.Core/DataBase/dbMigrator.cs
> +namespace Lapka.Files.Core.DataBase;
Do infrastruktury

2022-07-12 06:57 UTC, adambednarz commented on Lapka.Files.Core/Domain/Models/FileDetail.cs
> +public class FileInfoConfiguration : IEntityTypeConfiguration<FileDetail>
Dawanie dwóch klas w jednym pliku nie jest dobrym pomysłem jeżeli już  coś jest mocno powiązane to lepiej opakować to we wspólny katalog.
Poza tym ta konfiguracja to chyba już kwestia stricte infrastrukturalna co? a więc czy powinna się tu znajdować?

2022-07-12 06:57 UTC, adambednarz commented on Lapka.Files.Core/Migrations/20220707080101_fileDetails.cs
> +namespace Lapka.Files.Core.Migrations
Migracje do infrastruktury

2022-07-12 06:57 UTC, adambednarz commented on Lapka.Files.Core/Minio/FilesMinioClient.cs
> +public class FilesMinioClient
Minio do infrastruktury

2022-07-12 06:57 UTC, adambednarz commented on Lapka.Files.Infrastructure/Exceptions/FileException.cs
> +public class FileNotFoundInMinioException : ProjectException
Każda klasa powinna mieć swój plik

2022-07-12 06:57 UTC, adambednarz commented on Lapka.Files.Infrastructure/Exceptions/FileException.cs
> +public class FileNotFoundInPostgresException : ProjectException
ProjectException ma również właściwość status code to należałoby ją nadpisywać w każdym errorze

2022-07-12 06:57 UTC, adambednarz commented on Lapka.Files.Infrastructure/Repositories/Interfaces/IFileRepository.cs
> +public interface IFileRepository
Interfejs czyli reprezentacja naszego niezmiennego kontraktu powinna być w warstwie Core a wyłącznie implementacja powinna znajdować się w infrastrukturze

2022-07-12 06:57 UTC, adambednarz commented on Lapka.Files.Infrastructure/Repositories/Interfaces/IMinioRepository.cs
> +public interface IMinioRepository
Czy aby na pewno powinniśmy mieć coś takiego jak minio repository? Repozytorium tworzymy dla klas/obiektów czy też dla infrastrukturalnych elementów?

2022-07-12 06:57 UTC, adambednarz commented on Lapka.Files.Infrastructure/Repositories/MinioRepository.cs
> +        var bucket = new MinioBucket(_minioClient);
Nieco lepszym i prostszym pomysłem byłoby stworzenie prywatnej metody w tej samej klasie a niżeli tworzenie nowej klasy pod srawdzanie i  budowanie bucketów.

2022-07-12 06:57 UTC, adambednarz commented on Lapka.Files.Infrastructure/Repositories/MinioRepository.cs
> +    public MinioRepository(FilesMinioClient minioClient)
Dobrą praktyką jest dbanie o to aby konstruktory zawsze przyjmowały interfejsy, (oczywiście sa wyjątki jak np settingsy ale i tutaj można bazować na interfejsie IOptions<...>) więc nie wstrzykiwałbym klasy a klienta skonfigurował bezpośrednio w konstruktorze.

2022-07-12 06:57 UTC, adambednarz commented on Lapka.Files.Infrastructure/Services/StorageService.cs
> +internal class StorageService : IStorageClient
niespójnośc nazewnictwa   "StorageService : IStorageClient" to albo mamy klienta albo serwis. 
Unikamy takich rozwiązań bo po jakimś czasie nawigacja po takim kodzie jest bardzo trudna

2022-07-12 06:57 UTC, adambednarz commented on Lapka.Files.Infrastructure/Services/StorageService.cs
> +        await _minioRepository.DownloadFile(fileDto);
W związku z niepoprawnym zrozumieniem zamysłu użycia fasady pojawiło tu się repozytorium a powinna właśnie fasada

2022-07-12 06:57 UTC, adambednarz commented on Lapka.Files.Infrastructure/Services/StorageService.cs
> +        try
Dobre zabezpieczenie ale można to zrobić nieco inaczej, co dla nas stanowi większy problem podczas zapisu  a co podczas odczytu jeżeli coś pójdzie nie tak i dodamy plik najpierw do minio a do postgresa nie czy odwrotnie? Do przemyślenia

2022-07-12 06:57 UTC, adambednarz commented on Lapka.Files.Infrastructure/Services/StorageService.cs
> +            throw;
Jak już coś rzucamy to warto wiedzieć co ;)

2022-07-12 06:57 UTC, adambednarz commented on docker-compose.yml
> +      POSTGRES_PASSWORD: postgres
Zawsze podajemy dokładną wersję, bo za 2 lata ktoś odpali kod i może się okazać że pobierze dużo nowaszą wersję bazy niż ta na której my pracujemy i może spowodować to komplikacje

2022-07-12 06:57 UTC, adambednarz commented on docker-compose.yml
> +      - ./volumes/postgres:/var/lib/postgresql/data
podobnie w przypadku volumes dobrze przynajmniej zawrzeć w ścieżce z jakiej to jest bazy

2022-07-12 09:54 UTC, Madzionator commented on Lapka.Files.Infrastructure/Exceptions/FileException.cs
> +public class FileNotFoundInPostgresException : ProjectException
Ma wartość domyślną ustawioną na BadRequest

2022-07-14 06:39 UTC, adambednarz reviewed
Wpadło jeszcze kilka bardzo drobnych uwag ale całość ogólnie bardzo dobrze.

2022-07-14 06:39 UTC, adambednarz commented on Lapka.Files.Api/Controllers/StorageController.cs
> +        var fileDto = new FilePayload(stream, file.ContentType, file.FileName);
Ale sie uparliście żeby przekazywać stream. Zwracałem ostatnio uwagę że takie przekazywanie przy bardziej skomplikowanych operacjach może powodować komplikacje. Fakt jest lepiej bo masz użytą dyrektywę "using" ale mimo wszystko nie ma potrzeby otwierania stream'a już na etapie kontrollera

2022-07-14 06:39 UTC, adambednarz commented on Lapka.Files.Infrastructure/EntityConfigurations/FileInfoConfiguration.cs
> +public class FileInfoConfiguration : IEntityTypeConfiguration<FileDetail>
Przykładaj uwagę do spójnego nazewnictwa.
Klasa domenowa nazywa się FileDetail a konfiguracyjna FileInfo

2022-07-14 06:39 UTC, adambednarz commented on Lapka.Files.Infrastructure/Services/FileRules.cs
> +        return _validExtensions.Contains(fileExtension);
dobrze byłoby dodać ignorowanie porównywania wielkich małych liter

2022-07-20 06:22 UTC, adambednarz approved these changes

2022-08-26 09:14 UTC, merged